version: "3.9"
services:
  api-user:
    image: api-user
    container_name: api-user-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    networks:
      - spring-network
    depends_on:
      - mysql
  mysql:
    image: mysql
    container_name: mysql_database
    environment:
      MYSQL_ROOT_PASSWORD: 71390d49-66ee-4771-9f1a-d9020ee481e3
      MYSQL_USER: developer
      MYSQL_PASSWORD: developer_1
    ports:
      - "3309:3306"
    volumes:
      - mysql-volume:/var/lib/mysql
networks:
  spring-network:
volumes:
  mysql-volume:
