# peticones
GET http://localhost:3001/api/users

## crear
## 

POST  http://localhost:3001/api/users HTTP/1.1
Content-Type: application/json
Host: localhost:3001

{
    "name": "dEjempsaaalo Nmbre",
    "email": "ejempsssaos.email@dominio.com",
    "password": "cosanodasnaopds614"
    // Añade aquí todos los campos que tu endpoint POST /api/users espera en el cuerpo JSON
    // basándote en la estructura de tu entidad o DTO que recibe el controlador.
}
